jQuery('.test')
    .find('.child')
    .addClass('red')
    .addClass('blue')
    .end()
    .addClass('yellow')

// const api1 = jQuery('.test')
// const api2 = api1.find('.child').addClass('red').addClass('blue')
// const oldApi = api2.end().addClass('yellow')
